/*
 * ----- CLEO -----
 * File: environment.yml
 * Project: CLEOfire
 * Created Date: Thursday 12th October 2023
 * Author: Clara Bayley (CB)
 * Additional Contributors:
 * -----
 * Last Modified: Thursday 12th October 2023
 * Modified By: CB
 * -----
 * License: BSD 3-Clause "New" or "Revised" License
 * https://opensource.org/licenses/BSD-3-Clause
 * -----
 * Copyright (c) 2023 MPI-M, Clara Bayley
 */


name: enviropy3
dependencies:
    - python>=3.9
    - pytest
    - sphinx
