name: Build

on:
  pull_request:
  push:
    branches: [ci_build]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake

    - name: Build
      run: |
        mkdir build && cd build
        cmake -DKokkos_ARCH_NATIVE=ON -DKokkos_ENABLE_SERIAL=ON ..
        make
