/*
 * ----- CLEO -----
 * File: CI.yml
 * Project: workflows
 * Created Date: Thursday 12th October 2023
 * Author: Clara Bayley (CB)
 * Additional Contributors:
 * -----
 * Last Modified: Thursday 12th October 2023
 * Modified By: CB
 * -----
 * License: BSD 3-Clause "New" or "Revised" License
 * https://opensource.org/licenses/BSD-3-Clause
 * -----
 * Copyright (c) 2023 Clara Bayley
 */



name: Python test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: mypackage
          environment-file: environment.yml
          auto-activate-base: false
      - run: |
          conda info
          conda list
      - name: Install package
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install .
          python3 -m pip install -U sphinx
          python3 -m pip install -U numpy 
      - name: Test with pytest
        run: pytest .

      - name: Build docs
        run: |
          cd docs && make html
      - name: Archive build artifacts (i.e. documentation)
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: |
            docs/build
  # publish:
  #   needs: build
  #   # Only publish documentation when merging into `origin/main`.`
  #   if: "github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository_owner == 'yoctoyotta1024'"
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Download compiled book
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: docs
  #         path: build
  #     - name: Publish book on github pages
  #       uses: peaceiris/actions-gh-pages@v3
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         publish_dir: build/html
