name: "Sphinx: Render docs"

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: mypackage
        environment-file: environment.yml
        auto-activate-base: false
    - run: |
        conda info
        conda list
    - name: Install package
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install .
        python3 -m pip install -U sphinx
        python3 -m pip install -U numpy 
        python3 -m pip install -U furo 

    - name: Build HTML
      uses: ammaraskar/sphinx-action@master
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: html-docs
        path: docs/build/html/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html